### ISSUE TITLE
Port 8080 clashes with wordpress

### ISSUE THREAD

**Issue by Woofweasel** [kmr-ankitt/szare#1]
Hi there, I am excited to get this program working on my server! Thanks for your work on it. Unfortunately, I have a WordPress docker container installed that has to use the port 8080. Could you help me change your project to use a different port? I attempted to fork my own but couldn't get it working since I am completely inexperienced.

In my fork, I found the port mentioned in 2 files and changed both to the one I wanted:

/cmd/szare/main.go
and
/client/package.json

Unfortunately, the program still attempted to boot using port 8080 when I ran it.

**Comment by kmr-ankitt** [comment]
That is due to client directory defined in `cmd/utlis/utils.go`.
But, I changed port 8080 to 3002 as 8080 & 3000 are most used  ports.

**Comment by Woofweasel** [comment]
Thank you for this fix- that worked perfectly.
